$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:2
        },
        600:{
            items:3
        },
        800:{
            items:5
        },
        1000:{
            items:6
        },
        1250:{
            items:7
        },
        1500:{
            items:8
        }
    }
})